name: Format

on:
  workflow_call:
    inputs:
      package-path:
        required: true
        type: string

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      - name: Install dependencies
        run: pip install .[dev]
      - name: Ruff format check
        run: ruff format --check ${{ inputs.package-path }}