name: Build Python Package (Pull Request)

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  pr-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install building dependency
        run: python -m pip install build

      - name: Build distributions
        id: build_step
        run: python -m build

      - name: Comment on success
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "✅ Build succeeded!"
            })

      - name: Comment on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "❌ Build failed!"
            })