name: Build and Deploy Docs

on:
  release:
    types: [published]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-autodoc-typehints sphinx-rtd-theme
          pip install .  # Damit autodoc deine Module findet

      - name: Build Sphinx docs
        working-directory: docs
        run: |
          make html

      - name: Generate API docs
        run: sphinx-apidoc -o docs pyplantsim/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          # branch: gh-pages # Standard, nur anpassen falls nötig